all: cython

cython:
	python setup.py build_ext -i

install: cython
	pip install -e .

clean: cython-clean
	find -name '*.so' | xargs rm -rf
	rm -rf build
	rm -rf *.egg-info
	rm -rf .coverage coverage-report
	find -name '*.pyc' -exec rm {} \;
	find -name '*.so' -exec rm {} \;
	find -name '*.html' -exec rm {} \;

test: all
	python -c 'import lazygrad.adagrad as a; a.test()'

cython-clean:
	(cd lazygrad ; find . -name '*.cpp'  -print0 |xargs -0 ack --print0 --files-with-matches '/\* Generated by Cython' |xargs -0 rm -f)
	(cd lazygrad ; find . -name '*.c'    -print0 |xargs -0 ack --print0 --files-with-matches '/\* Generated by Cython' |xargs -0 rm -f)
	(cd lazygrad ; find . -name '*.html' -print0 |xargs -0 ack --print0 --files-with-matches 'Generated by Cython'     |xargs -0 rm -f)
